# Purpose:  Expose Metadata from a single Quilt bucket in Athena
#===============================================================================
# https://aws.amazon.com/cloudformation/resources/templates/
# https://catalog.us-east-1.prod.workshops.aws/workshops/9981f1a1-abdc-49b5-8387-cb01d238bb78/en-US/20-howtostart/201-self-paced/2013-cloudformation
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/walkthrough-crossstackref.html

AWSTemplateFormatVersion: "2010-09-09"
Description: Configure Athena tables for a Quilt Bucket
Parameters:
  QuiltAthenaStack:
    Description: The parent stack that defined the Athena Database, Workgroup and Bucket
    Type: String
    MinLength: 1
    MaxLength: 128
    AllowedPattern: '[a-zA-Z][-a-zA-Z0-9]*'
  QuiltBucket:
    Description: Name of an S3 Bucket containing Quilt packages
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '[a-z][-a-z0-9]*'
  QuiltBucketID:
    Description: |
      SQL-compatible string similar to the of QuiltBucket name,
      to use as a prefix for generated resources
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '[a-z][_a-z0-9]*'

#
# Input Parsing
#

# Glue TABLE
## https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html
## https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-SerDeInfo

# StorageDescriptor
## https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-StorageDescriptor

# SerdeInfo
## https://docs.aws.amazon.com/athena/latest/ug/supported-serdes.html
## https://github.com/apache/hive/blob/master/serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazySimpleSerDe.java

Resources:

  ManifestsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      TableInput:
        Name: !Sub "${QuiltBucketID}_quilt_manifests"
        Description: !Sub "Table of all the manifests in s3://${QuiltBucket} (all package-level and object-level metadata)"
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: false
        StorageDescriptor:
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              ignore.malformed.json: true
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          Location: !Sub "s3://${QuiltBucket}/.quilt/packages"
          Columns:
          - Name: logical_key
            Type: string
          - Name: physical_keys
            Type: array<string>
          - Name: size
            Type: bigint
          - Name: hash
            Type: struct<type:string,value:string>
          - Name: meta
            Type: string
          - Name: user_meta
            Type: string
          - Name: message
            Type: string
          - Name: version
            Type: string

  PackagesTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      TableInput:
        Name: !Sub "${QuiltBucketID}_quilt_packages"
        Description: !Sub "Table of top hashes in s3://${QuiltBucket}"
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
          Location: !Sub "s3://${QuiltBucket}/.quilt/named_packages"
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
          Columns:
          - Name: top_hash
            Type: string

  PackagesViewCreator:
    Type: AWS::Athena::NamedQuery
    Properties:
      WorkGroup:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-workgroup"
      Database:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      Name: !Sub "create1_${PackagesTable}_view"
      Description: !Sub "Quilt Query to create View from ${PackagesTable}"
      QueryString: !Sub |
        CREATE OR REPLACE VIEW "${QuiltBucketID}_quilt_packages_view" AS
        WITH
          npv AS (
          SELECT
            regexp_extract("$path", '^s3://[^/]+/[^/]+/[^/]+/([^/]+/[^/]+)', 1) pkg_name
          , regexp_extract("$path", '[^/]+$') timestamp
          , top_hash
          FROM
            "${PackagesTable}"
        )
        , mv AS (
          SELECT
            regexp_extract("$path", '[^/]+$') top_hash
          , manifest."user_meta"
          , manifest."message"
          FROM
            "${ManifestsTable}" manifest
          WHERE (manifest."logical_key" IS NULL)
        )
        SELECT
          npv."pkg_name"
        , npv."top_hash"
        , npv."timestamp"
        , mv."message"
        , mv."user_meta"
        FROM
          (npv
        INNER JOIN mv ON (npv."top_hash" = mv."top_hash"))

  ObjectsViewCreator:
    Type: AWS::Athena::NamedQuery
    Properties:
      WorkGroup:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-workgroup"
      Database:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      Name: !Sub "create2_${QuiltBucketID}_quilt_objects_view"
      Description: !Sub "Quilt Query to create View from ${ManifestsTable}"
      QueryString: !Sub |
        CREATE OR REPLACE VIEW "${QuiltBucketID}_quilt_objects_view" AS
        WITH
          npv AS (
          SELECT
            regexp_extract("$path", '^s3://[^/]+/[^/]+/[^/]+/([^/]+/[^/]+)', 1) pkg_name
          , regexp_extract("$path", '[^/]+$') timestamp
          , top_hash
          FROM
            "${PackagesTable}"
        )
        , mv AS (
          SELECT
            regexp_extract("$path", '[^/]+$') top_hash
          , manifest."logical_key"
          , manifest."physical_keys"
          , manifest."size"
          , manifest."hash"
          , manifest."meta"
          , manifest."user_meta"
          FROM
            "${ManifestsTable}" manifest
          WHERE (manifest."logical_key" IS NOT NULL)
        )
        SELECT
          npv."pkg_name"
        , npv."top_hash"
        , npv."timestamp"
        , mv."logical_key"
        , mv."physical_keys"[1] physical_key
        , mv."size"
        , mv."hash"
        , mv."meta"
        FROM
          (mv
        INNER JOIN npv ON (npv."top_hash" = mv."top_hash"))

  ObjectsViewTest:
    Type: AWS::Athena::NamedQuery
    Properties:
      WorkGroup:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-workgroup"
      Database:
        Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      Name: !Sub "preview_${QuiltBucketID}_quilt_objects_view"
      Description: !Sub "Preview data from ${ManifestsTable}"
      QueryString: !Sub 'SELECT * FROM "${QuiltBucketID}_quilt_objects_view" LIMIT 20'

Outputs:
  ManifestsTable:
    Value: !Ref ManifestsTable
    Export:
      Name: !Sub "${AWS::StackName}-manifests-table"
  PackagesTable:
    Value: !Ref PackagesTable
    Export:
      Name: !Sub "${AWS::StackName}-packages-table"
  ObjectsView:
    Value: !Sub "${QuiltBucketID}_quilt_objects_view"
    Export:
      Name: !Sub "${AWS::StackName}-objects-view"
  PackagesView:
    Value: !Sub "${PackagesTable}_view"
    Export:
      Name: !Sub "${AWS::StackName}-packages-view"
  PackagesViewCreator:
    Value: !Ref PackagesViewCreator
    Export:
      Name: !Sub "${AWS::StackName}-packages-view-creator"
  ObjectsViewCreator:
    Value: !Ref ObjectsViewCreator
    Export:
      Name: !Sub "${AWS::StackName}-objects-view-creator"
