# Purpose:  Enable Athena functionality from Quilt web catalog
#===============================================================================
# aws cloudformation validate-template --template-body file://athena/athena_cfn.yml
#  Scoped to ${AWS::StackName}

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Enable Athena from Quilt - Creates Athena Workgroup, Bucket, Policy

Parameters:
  DatabaseName:
    Default: default
    NoEcho: false
    Description: Name of an EXISTING Athena database to use for Quilt tables
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-z][_a-z]*'
  DatabaseTableRegex:
    Default: '*_quilt_*'
    NoEcho: false
    Description: Regexp for Quilt-created Tables
    Type: String
  SuffixBucket:
    Default: output
    NoEcho: false
    Description: Suffix for per-workgroup Athena output bucket
    Type: String
    MinLength: 3
    AllowedPattern: '[a-z][a-z0-9]*'
  SuffixWorkGroup:
    Default: query
    NoEcho: false
    Description: Suffix for Quilt-specific Athena workgroup
    Type: String
    MinLength: 3
    AllowedPattern: '[a-z][a-z0-9]*'

# Non-parameters (no intrinsics allowed)
# ARNDatacatalog: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:datacatalog/*'
# ARNCatalog:!Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'

Resources:
  QuiltAthenaOutput:
    Type: "AWS::S3::Bucket"
    #DeletionPolicy: Retain
    Properties:
      BucketName: !Join ["-", [!Ref AWS::StackName, !Ref SuffixWorkGroup, !Ref SuffixBucket]]

  QuiltAthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    DeletionPolicy: Delete
    Properties:
      Name: !Join ["-", [!Ref AWS::StackName, !Ref SuffixWorkGroup]]
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          OutputLocation: !Join ["", ["s3://" , Ref: QuiltAthenaOutput, "/"]]

  QuiltAthenaAccess:
    DeletionPolicy: Delete
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: /
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AccessAllAthenaWorkgroups
          Effect: Allow
          Action: athena:ListWorkGroups
          Resource: '*'
        - Sid: AccessQuiltAthenaWorkgroup
          Effect: Allow
          Action:
          - athena:Create*
          - athena:*Get*
          - athena:List*
          - athena:StartQueryExecution
          Resource:
          - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
          - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:datacatalog/*'
          - !Sub
            - 'arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${Workgroup}'
            - {Workgroup: !Ref QuiltAthenaWorkgroup}

        - Sid: AccessGlueDatabases
          Effect: Allow
          Action:
          - glue:GetDatabase
          - glue:GetDatabases
          - glue:GetTable
          - glue:GetTables
          Resource: '*'
        - Sid: ModifyGlueDatabases
          Effect: Allow
          Action:
          - glue:CreateTable
          - glue:DeleteTable
          - glue:UpdateTable
          Resource:
          - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
          - !Sub
            - 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${Database}'
            - {Database: !Ref DatabaseName}
          - !Sub
            - 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${Database}/${Tables}'
            - {Database: !Ref DatabaseName, Tables: !Ref DatabaseTableRegex}
        - Sid: AccessQuiltAthenaOutputBucket
          Effect: Allow
          Action:
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:ListMultipartUploadParts
          - s3:AbortMultipartUpload
          - s3:CreateBucket
          - s3:PutObject
          - s3:PutBucketPublicAccessBlock
          Resource:
          - !GetAtt QuiltAthenaOutput.Arn
          - !Join ["/", [!GetAtt QuiltAthenaOutput.Arn, '*']]

Outputs:
  AthenaPolicy:
    Description: IAM Policy used by Quilt to access Athena resource
    Value: !Ref QuiltAthenaAccess
    Export:
      Name: !Sub "${AWS::StackName}-policy"
  Database:
    Description: Name of Database used for Quilt package tables
    Value: !Ref DatabaseName
    Export:
      Name: !Sub "${AWS::StackName}-database"
  OutputBucket:
    Description: S3 bucket used by Quilt Workgroup
    Value: !Ref QuiltAthenaOutput
    Export:
      Name: !Sub "${AWS::StackName}-bucket"
  Workgroup:
    Description: Athena Workgroup used by Quilt
    Value: !Ref QuiltAthenaWorkgroup
    Export:
      Name: !Sub "${AWS::StackName}-workgroup"

