# Purpose:  Expose Metadata from a single Quilt bucket in Athena
#===============================================================================
# https://aws.amazon.com/cloudformation/resources/templates/
# https://catalog.us-east-1.prod.workshops.aws/workshops/9981f1a1-abdc-49b5-8387-cb01d238bb78/en-US/20-howtostart/201-self-paced/2013-cloudformation
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/walkthrough-crossstackref.html

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Configure Athena tables for a Quilt Bucket

Parameters:
  QuiltBucket:
    NoEcho: false
    Description: Name of an S3 Bucket containing Quilt packages
    Type: String
    MinLength: 1
    AllowedPattern: '[a-z][-a-z0-9]*'
  QuiltBucketID:
    NoEcho: false
    Description: SQL-compatible version of QuiltBucket name, to use as a prefix
    Type: String
    MinLength: 1
    AllowedPattern: '[a-z][_a-z0-9]*'
  QuiltAthenaStack:
    NoEcho: false
    Description: Parent stack defining Athena Database, Workgroup and Bucket
    Type: String
    MinLength: 1
    AllowedPattern: '[a-zA-Z][-a-zA-Z0-9]*'

#
# Input Parsing
#

# Glue TABLE
## https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html
## https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-SerDeInfo

# StorageDescriptor
## https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-StorageDescriptor

# SerdeInfo
## https://docs.aws.amazon.com/athena/latest/ug/supported-serdes.html
## https://github.com/apache/hive/blob/master/serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazySimpleSerDe.java

Resources:
  PackagesTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName:
        - Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      TableInput:
        Name:
        - !Sub
          - "${BucketID}_quilt_packages"
          - !BucketID Ref QuiltBucketID
        Description:
        - !Sub
          - "Make package top hashes from in s3://${Bucket} available in Athena"
          - !Bucket Ref QuiltBucket
        TableType: EXTERNAL_TABLE
        Properties:
          has_encrypted_data: false
          transient_lastDdlTime: 1557626200
        StorageDescriptor:
          Location:
          - !Sub
            - "s3://${Bucket}/.quilt/named_packages"
            - !Bucket Ref QuiltBucket
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
                 field.delim: ','
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
          Columns:
          - Name: hash
            Type: string
  ManifestTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName:
        - Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      TableInput:
        Name:
        - !Sub
          - "${BucketID}_quilt_manifests"
          - !BucketID Ref QuiltBucketID
        Description:
        - !Sub
          - "Table of all the manifests in s3://${Bucket} (all package-level and object-level metadata)"
          - !Bucket Ref QuiltBucket
        TableType: EXTERNAL_TABLE
        Properties:
          has_encrypted_data: false
        StorageDescriptor:
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              ignore.malformed.json: true
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
          Location:
          - !Sub
            - "s3://${Bucket}/.quilt/packages"
            - !Bucket Ref QuiltBucket
          Columns:
          - Name: logical_key
            Type: string
          - Name: physical_keys
            Type: array<string>
          - Name: size
            Type: bigint
          - Name: hash
            Type: struct<type:string,value:string>
          - Name: meta
            Type: string
          - Name: user_meta
            Type: string
          - Name: message
            Type: string
          - Name: version
            Type: string


  PackagesTableQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database:
      - Fn::ImportValue: !Sub "${QuiltAthenaStack}-database"
      Name:
        Fn::Sub:
        - "${Table} preview"
        - !Table Ref PackagesTable
      Description:
      - !Sub
        - "First few rows of ${Table} from s3://${Bucket}"
        - !Table Ref PackagesTable
        - !Bucket Ref QuiltBucket
      QueryString:
      - !Sub
        - "select * from ${Table} limit 10;"
        - !Table Ref PackagesTable
      WorkGroup:
      - Fn::ImportValue: !Sub "${QuiltAthenaStack}-workgroup"

Outputs:
  PackagesTableQuery:
    Description: !Ref PackagesTableQuery.Description,
    Value: !Ref PackagesTableQuery
    Export:
      Name: !Sub "${AWS::StackName}-query-package-table"

