# Purpose:  Enable Athena functionality from Quilt web catalog
#===============================================================================
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Enable Athena from Quilt - Creates Athena Workgroup, Bucket, Policy

Parameters:
  YourCompany:
    NoEcho: false
    Description: Label representing your company, for use in naming buckets
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  WorkgroupName:
    Default: quilt-workgroup
    NoEcho: false
    Description: Name for Quilt-specific Athena workgroup
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-z][-a-z0-9]*'
  PolicyName:
    Default: AthenaQuiltAccess
    NoEcho: false
    Description: Granting Quilt access to these Athena resources
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[A-Z][a-zA-Z0-9]*'
  OutputBucket:
    Default: athena-quilt-output
    NoEcho: false
    Description: Suffix used for per-account Athena output bucket
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-z][-a-z0-9]*'
  DatabaseName:
    Default: quilt_metadata
    NoEcho: false
    Description: Name for Quilt-specific Athena database
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-z][_a-z]*'
  DatabaseTableRegex:
    Default: *_quilt_*
    NoEcho: false
    Description: Regexp for Quilt-created Tables
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-z][_a-z]*'
  ARNDatacatalog:
    Default: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:datacatalog/*'
    NoEcho: false
    Description: Datacatalog(s) Quilt can access
    Type: String
    AllowedPattern: 'arn:aws:[a-zA-Z0-9-:]+'
  ARNCatalog:
    Default: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
    NoEcho: false
    Description: Catalog Quilt can access
    Type: String
    AllowedPattern: 'arn:aws:[a-zA-Z0-9-:]+'

Resources:
  AthenaQuiltOutput:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join ["-", !Ref YourCompany, !Ref BucketSuffix]

  AthenaQuiltWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Ref WorkgroupName
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          OutputLocation: !Join [ "", ["s3://" , Ref: AthenaQuiltOutput, "/"]]

  # https://docs.aws.amazon.com/glue/latest/dg/populate-with-cloudformation-templates.html
  AthenaQuiltDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName
        Description: Database for all Quilt Metadata
        #LocationUri: ' '

  AthenaQuiltAccess:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref PolicyName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AccessAllAthenaWorkgroups
          Effect: Allow
          Action: athena:ListWorkGroups
          Resource: *
        - Sid: AccessAthenaQuiltWorkgroup
          Effect: Allow
          Action:
          - athena:Create*
          - athena:Get*
          - athena:ListDatabases
          - athena:ListNamedQueries
          - athena:ListPreparedStatements
          - athena:ListQueryExecutions
          - athena:StartQueryExecution
          Resource:
          - !Ref AthenaQuiltWorkgroup
          - !Ref ARNCatalog
          - !Ref ARNDatacatalog
        - Sid: AccessGlueDatabases
          Effect: Allow
          Action:
          - glue:GetDatabase
          - glue:GetDatabases
          - glue:GetTable
          - glue:GetTables
          Resource: *
        - Sid: ModifyGlueDatabases
          Effect: Allow
          Action:
          - glue:CreateTable
          - glue:DeleteTable
          - glue:UpdateTable
          Resource:
          - !Ref ARNCatalog
          - !Ref AthenaQuiltDatabase
          - !Sub
            - 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${Database}/{Tables}'
            - !Database Ref DatabaseName
            - !Tables Ref DatabaseTableRegex
        - Sid: AccessQuiltAthenaOutputBucket
          Effect: Allow
          Action:
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:ListMultipartUploadParts
          - s3:AbortMultipartUpload
          - s3:CreateBucket
          - s3:PutObject
          - s3:PutBucketPublicAccessBlock
          Resource:
          - !Ref AthenaQuiltOutput

Outputs:
  AthenaQuiltWorkgroup:
    Description: Athena Workgroup used by Quilt
    Value: !Ref AthenaQuiltWorkgroup
  AthenaQuiltPolicy:
    Description: IAM Policy used by Quilt to access Athena resource
    Value: !Ref AthenaQuiltAccess
  AthenaQuiltOutputBucket:
    Description: S3 bucket used by Quilt Workgroup
    Value: !Ref AthenaQuiltOutput

